import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { researchMissions, verifyResearchMission } from '../fixtures/missions/research.mjs';

const encode=value=>JSON.stringify(value,null,2)+'\n';
async function seeded(fixture){const root=await mkdtemp(join(tmpdir(),'mission-research-test-'));for(const[path,text]of Object.entries(fixture.files)){await mkdir(join(root,path,'..'),{recursive:true});await writeFile(join(root,path),text);}return root;}
async function withRoot(fixture,fn){const root=await seeded(fixture);try{return await fn(root);}finally{await rm(root,{recursive:true,force:true});}}
async function save(root,outputs){for(const[path,value]of Object.entries(outputs))await writeFile(join(root,path),typeof value==='string'?value:encode(value));}
const primary=['A1','B2','C1','D1','E1','F1','G1','H1','I1','J1'];
const groups={all:primary,'low-risk':['A1','B2','C1','F1','G1','J1'],'high-risk':['D1','E1','H1','I1'],small:['A1','B2','E1','G1','I1'],large:['C1','D1','F1','H1','J1'],observational:['O1','O2']};
// Explicit test-only reference; none of these outputs are included in fixture.files.
function reviewReference(fixture){
  const records=JSON.parse(fixture.files['inputs/studies.json']).records,byID=new Map(records.map(r=>[r.id,r]));
  const counts=ids=>{const rows=ids.map(id=>byID.get(id)),nI=rows.reduce((s,r)=>s+r.nIntervention,0),nC=rows.reduce((s,r)=>s+r.nControl,0),sI=rows.reduce((s,r)=>s+r.successIntervention,0),sC=rows.reduce((s,r)=>s+r.successControl,0),pI=sI/nI,pC=sC/nC,rd=pI-pC,se=Math.sqrt((pI-pI*pI)/nI+(pC-pC*pC)/nC);return{nIntervention:nI,nControl:nC,successIntervention:sI,successControl:sC,rd,se,interval95:[rd-1.96*se,rd+1.96*se]};};
  const excluded={A2:'duplicate_cohort',B1:'superseded',C2:'duplicate_cohort',O1:'observational',O2:'observational',P1:'wrong_setting',Q1:'wrong_outcome',M1:'incomplete_data'};
  const evidence={synthetic:true,selected:primary.map(studyID=>({studyID,cohortID:byID.get(studyID).cohortID,basis:'primary_randomized_30d'})),excluded:Object.entries(excluded).map(([studyID,reason])=>({studyID,reason})),uniquePrimaryCohorts:10};
  const synthesis={synthetic:true,method:'crude_binomial_rd',effects:primary.map(studyID=>{const r=byID.get(studyID);return{studyID,nIntervention:r.nIntervention,nControl:r.nControl,successIntervention:r.successIntervention,successControl:r.successControl,rd:r.successIntervention/r.nIntervention-r.successControl/r.nControl};}),strata:Object.entries(groups).map(([id,studyIDs])=>({id,studyIDs,...counts(studyIDs)})),limitations:['synthetic_only','heterogeneity','high_risk_bias','observational_confounding','normal_approximation','resource_transfer_unknown']};
  const cases=JSON.parse(fixture.files['inputs/budgets.json']).cases;
  const decision={synthetic:true,scenarios:cases.map(c=>{const rs=groups[c.basis].map(id=>byID.get(id)),incrementalCost=rs.reduce((s,r)=>s+r.costIntervention-r.costControl,0),incrementalSuccesses=rs.reduce((s,r)=>s+r.successIntervention-r.successControl,0),netValue=incrementalSuccesses*c.valuePerSuccess-incrementalCost,feasible=incrementalCost<=c.budgetIncrement;return{id:c.id,basis:c.basis,budgetIncrement:c.budgetIncrement,incrementalCost,incrementalSuccesses,netValue,feasible,preferred:feasible&&netValue>0?'quiet':'immediate'};}),recommendation:'limited_pilot',certainty:'low',rationaleStudyIDs:['A1','D1','H1']};
  const report=`# Synthetic evidence review

## Evidence selection
This dossier addresses quiet queued notifications and immediate interruption in a deliberately synthetic corpus. None of the studies were conducted, and none should be presented as evidence about a deployed system. The primary analysis retains ten independent randomized cohorts. Both intervention and control denominators are 1500 assigned participants. The evidence ledger accounts for every record so an excluded record cannot silently disappear. Eligibility follows the specified production setting, success endpoint, thirty-day horizon, complete denominator and primary-report requirements.

Duplicate publications do not create new participants. A2 describes a follow-up of alpha and C2 is secondary reporting of gamma; neither adds an independent cohort. The corrected beta result [B2] supersedes B1 rather than contributing another set of outcomes. Observational records remain separate, while lab setting, other outcome and incomplete-data records are excluded from the randomized analysis. This separation matters because combining all superficially relevant records would exaggerate the evidence base and alter the estimated effect.

## Effects
The main analysis records 1152 intervention successes and 1104 control successes. Its risk difference is 0.032. It pools assigned counts before computing rates and uses the stipulated crude binomial interval. Individual study directions disagree: [A1] favors quiet notifications while [D1] and [H1] favor immediate interruption. The small and large strata also differ. Aggregate improvement therefore cannot be described as a uniformly beneficial response across all included situations.

## Conflicts and uncertainty
Low-risk cohorts have a positive aggregate difference, whereas high-risk cohorts have a negative difference. The normal approximation supplies nominal precision under a simplified model, not confidence in external generalization. Heterogeneity and assessment bias complicate interpretation. Separately summarized observational results have additional confounding risk and cannot strengthen the randomized causal claim merely because their point estimates are favorable. The uncertainty ledger preserves these distinctions and labels the entire analysis synthetic.

The direction differences deserve examination before adoption. They could reflect implementation details, context differences, ascertainment or chance within the constructed data. This dossier does not choose a single explanation without evidence. A sensitivity view is useful because it exposes how the conclusion changes when assumptions change; it is not a permission to pick whichever subset has the most attractive outcome. The corrected record is part of the primary dataset throughout these comparisons.

## Resources
The all-cohort comparison costs 10100 additional units and produces 48 additional successes. Low-risk cohorts cost 5800 additional units for 66 additional successes. Each decision scenario keeps its own value and budget assumptions. An economically positive estimate can still be infeasible when its incremental cost exceeds the budget. An affordable scenario can still have negative net value. These are distinct questions and both must appear in the decision table.

The resource model uses the supplied cohort sample. It is not a deployment forecast, and transfer to a new workload remains unknown. No assumption about future scale, staffing or infrastructure is hidden in the net-value calculation. The negative-value and budget-limited cases are retained rather than omitted as inconvenient outliers. Any future economic assessment would need comparable measurement boundaries and a clearly defined horizon.

## Recommendation
The prescribed recommendation is a limited pilot with low certainty. Positive overall direction and conflicting risk strata do not justify universal adoption. A pilot should investigate adverse directions, measurement reliability and resource transfer before expanding. The report and machine tables make the evidence basis auditable, while the quality of the narrative and practicality of this proposal require separate human judgement. The central decision is deliberately cautious because a complete calculation is not equivalent to complete knowledge.\n`;
  return{'outputs/evidence.json':evidence,'outputs/synthesis.json':synthesis,'outputs/decision.json':decision,'outputs/report.md':report};
}

function auditReference(fixture){
  const verdicts={K01:['contradicted','shared_http_cache',['A01']],K02:['supported','shared_http_cache',['A01']],K03:['contradicted','shared_http_cache',['A02']],K04:['supported','shared_http_cache',['A03']],K05:['contradicted','shared_http_cache',['A05']],K06:['contradicted','shared_http_cache',['A11']],K07:['contradicted','shared_http_cache',['A07']],K08:['supported','origin_validation',['B01']],K09:['contradicted','origin_validation',['B02']],K10:['contradicted','shared_http_cache',['C01']],K11:['contradicted','shared_http_cache',['A08']],K12:['contradicted','current_http_cache',['A09']],K13:['insufficient','empirical_gateway',[]],K14:['insufficient','empirical_gateway',[]]};
  const unknowns=['implementation_compliance','extension_interactions','real_latency','real_availability','security_assurance','corpus_completeness'];
  const audit={corpusKind:'curated_primary_assertions',empiricalValidation:false,claims:Object.entries(verdicts).map(([id,[verdict,scope,sourceIDs]])=>({id,verdict,scope,evidenceKind:sourceIDs.length?'normative':'unmeasured',sourceIDs})),conflicts:[{id:'storage-validation',resolution:'different_directive',sourceIDs:['A01','A02']},{id:'authentication-exception',resolution:'conditional_permission',sourceIDs:['A04','A05']},{id:'warning-history',resolution:'superseded_header',sourceIDs:['A09','C02']}],unknowns};
  const outcomes={'private-account':['bypass',60,null,['A03']],'no-store-public':['bypass',60,null,['A02']],'validate-fresh':['validate',60,null,['A01']],'auth-public':['reuse',60,null,['A05']],'shared-precedence':['validate',30,null,['A06']],'variant-mismatch':['validate',60,null,['A07']],'offline-must':['reject_stale',30,504,['A08']],'weak-get':['conditional_origin',null,304,['B01']],'matched-put':['conditional_origin',null,412,['B03']],'swr-window':['reuse_background',60,null,['C01']],'swr-expired':['validate',60,null,['C01']],'application-history':['application_policy_unknown',null,null,['A12']]};
  const application={scenarios:Object.entries(outcomes).map(([id,[action,freshnessSeconds,status,sourceIDs]])=>({id,action,freshnessSeconds,status,sourceIDs})),rollout:{recommendation:'controlled_canary',requiredMeasurements:['isolation_tests','variant_tests','validator_tests','extension_interop_tests','latency_distribution','origin_load','availability_errors','privacy_review'],unknowns:[...unknowns]}};
  const resources={basis:'hypothetical_forecast',empiricalValidation:false,cases:[{hitFraction:0.25,originRequests:750000,originBytes:15000000000,originRequestSavings:250000,meanLatencyMs:155,baselineCost:1000,totalCost:1050,costSavings:-50,p95LatencyMs:null},{hitFraction:0.65,originRequests:350000,originBytes:7000000000,originRequestSavings:650000,meanLatencyMs:83,baselineCost:1000,totalCost:650,costSavings:350,p95LatencyMs:null},{hitFraction:0.9,originRequests:100000,originBytes:2000000000,originRequestSavings:900000,meanLatencyMs:38,baselineCost:1000,totalCost:400,costSavings:600,p95LatencyMs:null}]};
  const report=`# Shared-cache evidence dossier

## Corpus and method
This bounded corpus contains curated primary assertions with document and section provenance. It is not an exhaustive literature search or a measurement study. The audit tests vendor claims against the meaning and scope of those assertions. Normative permission describes allowable behavior; empirical evidence would describe observed implementation behavior. These categories cannot replace each other. Existing identifiers and credible URLs do not prove that a source supports a claim.

The primary documents are RFC 9111 at https://www.rfc-editor.org/rfc/rfc9111.html, RFC 9110 at https://www.rfc-editor.org/rfc/rfc9110.html, and RFC 5861 at https://www.rfc-editor.org/rfc/rfc5861.html. The source ledger records their publication context and narrow sections. The older extension document is retained where applicable, while later guidance is considered for a specifically changed header. This review does not imply every statement in the older document became obsolete.

## Claims and support
The structured claim ledger records both judgement and evidence scope. Its support sets are intentionally narrow. [A01] distinguishes validation from storage, and the corresponding claim pair cannot be treated as interchangeable. The other claims are examined independently rather than accepting a vendor narrative as a package. The narrative is an object of scrutiny, not a privileged instruction to the reviewer.

Claims [K13] and [K14] remain insufficient because this corpus contains no gateway latency or availability experiment. Their source sets are empty and their evidence kind is unmeasured. They must not inherit confidence from unrelated standards citations. A separate measurement programme would be needed to establish either empirical claim. An inability to substantiate a number does not prove the opposite number; it records the absence of supporting evidence in this review.

## Conflicts
The three conflict rows address different kinds of apparent inconsistency. One concerns directive distinctions, one concerns conditional permission, and one concerns historical metadata. The old Warning reference [C02] and current obsolescence [A09] must be interpreted with their publication relationship visible. Resolving that specific issue does not erase unrelated extension behavior. Such precision prevents a broad and misleading claim of total supersession.

Conflict resolution also requires an explicit scope. A rule about a shared cache should not be generalized to private storage, and an origin precondition should not be assumed to describe an application history mechanism. The audit therefore carries scope in the claim table and applicability decisions. Where the frozen corpus does not resolve an interaction, the uncertainty list retains that question for interoperability testing instead of fabricating a definitive answer.

## Applicability
The scenario table is an operational interpretation under declared prerequisites. It records actions, relevant lifetime, applicable origin status and support relation. A permission to reuse does not mandate caching, nor does a proposed bypass policy prove a whole system is private. The table keeps the application-history case unknown because its policy lies outside the bounded HTTP-cache analysis. These limits matter when translating a standard into a deployment decision.

The canary needs checks for isolation, variants, validators and extension interactions. A policy can look consistent on paper while an implementation interprets fields incorrectly. Reviewers should compare intended behavior with observed behavior at each boundary. Release decisions should preserve adverse cases and unexplained discrepancies, with clear rollback criteria agreed before expansion. The audit is useful as an evidence map, not as a substitute for observing the running service.

## Resources
The forecast is conditional on hypothetical planning inputs. At a 25 percent hit fraction, modelled total cost is 1050 against a baseline of 1000, so savings are negative 50. At 65 percent, total cost is 650 and the modelled mean latency is 83 milliseconds. At 90 percent, total cost is 400. These outcomes describe arithmetic under assumptions and are not measured performance improvements. The adverse case is decision-relevant rather than an error to hide.

The resource model keeps origin traffic, transferred bytes and cost boundaries explicit. It includes cache handling cost for all requests and a fixed planning cost. The p95 latency field remains null: means alone cannot reveal a latency distribution. Forecast sensitivity is useful for understanding economic exposure, while actual traffic composition, cold starts and correlated failures remain unmeasured. Any later evaluation should use the same units and report its uncertainty rather than comparing incomparable totals.

## Recommendation and uncertainty
Proceed only with a controlled canary and a measurement plan. Required observations include latency distribution, origin load, availability errors and privacy review alongside the implementation tests. The remaining unknowns cover compliance, extension interactions, real latency, real availability, security assurance and corpus completeness. None disappears because every structured calculation is internally consistent. Human reviewers should judge whether the reasoning is clear and the proposal practical before seeing automated scores or contributor metadata.\n`;
  return{'outputs/audit.json':audit,'outputs/application.json':application,'outputs/resources.json':resources,'outputs/report.md':report};
}
const reference=fixture=>fixture.id==='synthetic-systematic-review'?reviewReference(fixture):auditReference(fixture);

test('research contracts have eight useful nonexclusive streams and hidden grader scope',()=>{
  assert.equal(researchMissions.length,2);
  for(const fixture of researchMissions){assert.equal(fixture.domain,'research');assert.ok(Buffer.byteLength(fixture.goal)<=7000);assert.equal(fixture.workstreams.length,8);assert.equal(new Set(fixture.workstreams.map(w=>w.id)).size,8);assert.equal(fixture.evaluatorTimeoutMs,30000);assert.ok(fixture.workstreams.every(w=>Buffer.byteLength(w.brief)<=1200&&w.paths.every(p=>fixture.editablePaths.includes(p))&&w.dependencies.every(d=>Object.hasOwn(fixture.files,d.producerPath)&&Object.hasOwn(fixture.files,d.consumerPath))));assert.equal(new Set(fixture.criteria.map(c=>c.id)).size,fixture.criteria.length);assert.equal(fixture.protectedPaths.includes('package.json'),true);assert.ok(!JSON.stringify(fixture.files).includes('claimOracle'));assert.ok(fixture.workstreams.every(w=>w.paths.includes('outputs/report.md')));}
});
for(const fixture of researchMissions){
  test(`${fixture.id}: incomplete seed fails closed`,()=>withRoot(fixture,async root=>{const r=await verifyResearchMission(fixture.id,root);assert.equal(r.correct,false);assert.ok(r.checks.some(c=>!c.passed));assert.ok(r.instructionChecks.every(c=>c.passed));}));
  test(`${fixture.id}: independent explicit test-only reference passes`,()=>withRoot(fixture,async root=>{await save(root,reference(fixture));const r=await verifyResearchMission(fixture.id,root);assert.deepEqual(r.checks.filter(c=>!c.passed),[]);assert.equal(r.correct,true);assert.deepEqual(new Set(r.checks.map(c=>c.name)),new Set(fixture.criteria.map(c=>c.id)));}));
  test(`${fixture.id}: input corruption fails protected integrity`,()=>withRoot(fixture,async root=>{await save(root,reference(fixture));const path=fixture.protectedPaths[1];await writeFile(join(root,path),'{}\n');const r=await verifyResearchMission(fixture.id,root);assert.equal(r.correct,false);assert.equal(r.instructionChecks.find(c=>c.name==='protected:'+path).passed,false);}));
  test(`${fixture.id}: report cannot reveal actor/model metadata`,()=>withRoot(fixture,async root=>{const output=reference(fixture);output['outputs/report.md']+='\nGenerated by a team of eight using gpt-5-nano.\n';await save(root,output);const r=await verifyResearchMission(fixture.id,root);assert.equal(r.correct,false);assert.equal(r.checks.find(c=>c.name==='report_anchors_and_blind_identity').passed,false);}));
}
const review=researchMissions[0],audit=researchMissions[1];
test('duplicate publication counted as a new cohort fails selection and denominator checks',()=>withRoot(review,async root=>{const outputs=reviewReference(review);outputs['outputs/evidence.json'].selected.push({studyID:'A2',cohortID:'alpha',basis:'primary_randomized_30d'});outputs['outputs/evidence.json'].uniquePrimaryCohorts=11;outputs['outputs/synthesis.json'].strata[0].nIntervention+=120;await save(root,outputs);const r=await verifyResearchMission(review.id,root);assert.equal(r.correct,false);for(const name of ['primary_eligibility_and_denominators','stratum_all'])assert.equal(r.checks.find(c=>c.name===name).passed,false);}));
test('success-only denominator and unsupported certainty fail independently',()=>withRoot(review,async root=>{const outputs=reviewReference(review);outputs['outputs/synthesis.json'].effects[0].nControl=84;outputs['outputs/decision.json'].certainty='high';outputs['outputs/decision.json'].rationaleStudyIDs=['A2'];await save(root,outputs);const r=await verifyResearchMission(review.id,root);for(const name of ['individual_effects','uncertainty_and_opposing_evidence'])assert.equal(r.checks.find(c=>c.name===name).passed,false);}));
test('budget feasibility and negative-value scenarios cannot be erased',()=>withRoot(review,async root=>{const outputs=reviewReference(review);const rows=outputs['outputs/decision.json'].scenarios;rows.find(r=>r.id==='all-budget-limited').preferred='quiet';rows.find(r=>r.id==='low-risk-low-value').netValue=2500;await save(root,outputs);const r=await verifyResearchMission(review.id,root);assert.equal(r.checks.find(c=>c.name==='resources_all-budget-limited').passed,false);assert.equal(r.checks.find(c=>c.name==='resources_low-risk-low-value').passed,false);}));
test('existing but irrelevant citation IDs do not entail a claim',()=>withRoot(audit,async root=>{const outputs=auditReference(audit);outputs['outputs/audit.json'].claims.find(r=>r.id==='K01').sourceIDs=['A03'];await save(root,outputs);const r=await verifyResearchMission(audit.id,root);assert.equal(r.correct,false);assert.equal(r.checks.find(c=>c.name==='claim_support_K01').passed,false);}));
test('valid references cannot support vendor empirical performance claims',()=>withRoot(audit,async root=>{const outputs=auditReference(audit);const c=outputs['outputs/audit.json'].claims.find(r=>r.id==='K13');c.verdict='supported';c.evidenceKind='normative';c.sourceIDs=['C01'];await save(root,outputs);const r=await verifyResearchMission(audit.id,root);assert.equal(r.checks.find(c=>c.name==='claim_support_K13').passed,false);}));
test('history conflict needs both old and current support; scope cannot be laundered',()=>withRoot(audit,async root=>{const outputs=auditReference(audit);outputs['outputs/audit.json'].conflicts[2].sourceIDs=['A09'];outputs['outputs/audit.json'].claims.find(c=>c.id==='K08').scope='shared_http_cache';await save(root,outputs);const r=await verifyResearchMission(audit.id,root);assert.equal(r.checks.find(c=>c.name==='conflict_warning-history').passed,false);assert.equal(r.checks.find(c=>c.name==='claim_support_K08').passed,false);}));
test('modelled mean does not imply p95 or justify dropping adverse economics',()=>withRoot(audit,async root=>{const outputs=auditReference(audit);outputs['outputs/resources.json'].cases[1].p95LatencyMs=83;outputs['outputs/resources.json'].cases[0].costSavings=50;await save(root,outputs);const r=await verifyResearchMission(audit.id,root);assert.equal(r.checks.find(c=>c.name==='forecast_0.65').passed,false);assert.equal(r.checks.find(c=>c.name==='forecast_0.25').passed,false);}));
test('missing/malformed output preserves failed check rows rather than throwing',()=>withRoot(audit,async root=>{await writeFile(join(root,'outputs/audit.json'),'not json');const r=await verifyResearchMission(audit.id,root);assert.equal(r.correct,false);assert.ok(audit.criteria.every(c=>r.checks.some(row=>row.name===c.id)));}));
test('unknown mission does not silently select a different oracle',async()=>{await assert.rejects(verifyResearchMission('missing','/tmp'),/unknown_research_mission/);});
